# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Pixel Pathos
# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pixelpathos.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: warmsounduk
github_username:  warmsound

# Build settings
theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
show_downloads: false
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Custom variables
lumeo_store_url: https://apps.garmin.com/apps/1330c898-8d68-4744-8886-41c13ae55151
lumeo_kpay_store_url: https://apps.garmin.com/apps/22bb01ba-ace2-4662-8690-f4e56d0bdeb9
lumeo_kpay_trial_hours: 24

crystal_store_url: https://apps.garmin.com/apps/9fd04d09-8c80-4c81-9257-17cfa0f0081b
crystal_reborn_store_url: https://apps.garmin.com/apps/f3c3d2d3-6efa-49da-bdab-329cdf37b70f
crystal_reborn_kpay_store_url: https://apps.garmin.com/apps/111ed5fc-c61f-47ec-b05d-aac856024d06
crystal_reborn_kpay_trial_hours: 24

garmin_refund_url: https://support.garmin.com/en-GB/?faq=tAsPhqUXOo2L3guHjLpJa7
garmin_regions_url: https://developer.garmin.com/connect-iq/monetization/app-sales/
openweather_sign_up_url: https://home.openweathermap.org/users/sign_up
